import type { MarketUpdate } from "@/types/marketUpdate"

export const demoUpdates: MarketUpdate[] = [
  // Live Hospitality Index (non-SWAP jobs)
  {
    id: "1",
    type: "URGENT",
    title: "Head Chef Required - Michelin Star Restaurant",
    location: "Le Gavroche",
    rate: "£40/hr",
    highlight: true,
    created_at: new Date().toISOString(),
    region: "London, UK",
    currency: "GBP",
    original_rate: 40,
    currency_rate: 1,
    urgency_level: "high",
  },
  {
    id: "2",
    type: "PREMIUM",
    title: "Experienced Sommelier Needed",
    location: "The French Laundry",
    rate: "$45/hr",
    highlight: false,
    created_at: new Date().toISOString(),
    region: "Napa Valley, USA",
    currency: "USD",
    original_rate: 45,
    currency_rate: 1,
    urgency_level: "medium",
  },
  {
    id: "3",
    type: "URGENT",
    title: "Sous Chef Needed - 5* Hotel",
    location: "The Westin Excelsior",
    rate: "€35/hr",
    highlight: true,
    created_at: new Date().toISOString(),
    region: "Rome, Italy",
    currency: "EUR",
    original_rate: 35,
    currency_rate: 1,
    urgency_level: "high",
  },
  {
    id: "4",
    type: "PREMIUM",
    title: "Executive Pastry Chef",
    location: "The Test Kitchen",
    rate: "R400/hr",
    highlight: true,
    created_at: new Date().toISOString(),
    region: "Cape Town, South Africa",
    currency: "ZAR",
    original_rate: 400,
    currency_rate: 1,
    urgency_level: "medium",
  },
  {
    id: "5",
    type: "URGENT",
    title: "Banquet Server - VIP Event",
    location: "Fairmont Chateau Lake Louise",
    rate: "C$30/hr",
    highlight: false,
    created_at: new Date().toISOString(),
    region: "Alberta, Canada",
    currency: "CAD",
    original_rate: 30,
    currency_rate: 1,
    urgency_level: "high",
  },

  // Emergency & Shift Swap Index (URGENT and SWAP jobs)
  {
    id: "6",
    type: "SWAP",
    title: "Bartender Evening Shift Available",
    location: "Café del Mar",
    rate: "€25/hr",
    highlight: false,
    created_at: new Date().toISOString(),
    region: "Malta",
    currency: "EUR",
    original_rate: 25,
    currency_rate: 1,
    urgency_level: "medium",
  },
  {
    id: "7",
    type: "URGENT",
    title: "Emergency Kitchen Porter Needed",
    location: "Noma",
    rate: "DKK 200/hr",
    highlight: true,
    created_at: new Date().toISOString(),
    region: "Copenhagen, Denmark",
    currency: "DKK",
    original_rate: 200,
    currency_rate: 1,
    urgency_level: "high",
  },
  {
    id: "8",
    type: "SWAP",
    title: "Housekeeping Shift Swap Request",
    location: "Gleneagles Hotel",
    rate: "£18/hr",
    highlight: false,
    created_at: new Date().toISOString(),
    region: "Perthshire, Scotland",
    currency: "GBP",
    original_rate: 18,
    currency_rate: 1,
    urgency_level: "low",
  },
  {
    id: "9",
    type: "URGENT",
    title: "Last-Minute Event Coordinator",
    location: "Javits Center",
    rate: "$40/hr",
    highlight: true,
    created_at: new Date().toISOString(),
    region: "New York City, USA",
    currency: "USD",
    original_rate: 40,
    currency_rate: 1,
    urgency_level: "high",
  },
  {
    id: "10",
    type: "SWAP",
    title: "Front Desk Agent Shift Exchange",
    location: "Belmond Mount Nelson Hotel",
    rate: "R250/hr",
    highlight: false,
    created_at: new Date().toISOString(),
    region: "Cape Town, South Africa",
    currency: "ZAR",
    original_rate: 250,
    currency_rate: 1,
    urgency_level: "medium",
  },
]

